### ISSUE TITLE
Series of spaces in lyrics make the conversion fail (Empty group)

### ISSUE THREAD

**Issue by jose1711** [T045T/ultraloop#6]
Input (`cat -vte`):
```
#TITLE:Foo$
#ARTIST:bar$
#LANGUAGE:English$
#GENRE:Pop$
#YEAR:2020$
#MP3:Foo.mp3$
#COVER:Cover.jpg$
#VIDEO:Video.avi$
#END:300000$
#BPM:120$
#GAP:17800$
- 1165$
: 1169 5 1 foo$
: 1176 3 2 $
: 1181 1 2  $
: 1184 2 1 bar$
E$
```
Results in
```
..
[Lyrics]

L: $
@:  0

L: {foo} {}{bar}$
@: 1169  12 3 2
```
Which `blitzloop` is unable to process:
```
blitzloop.song.ParseError: Empty group, row 7, source: {foo} {}{bar}
```

**Comment by T045T** [comment]
Try the latest version, I think that should fix it – although, as the commit message says, I don't think that's a valid Ultrastar file. If it is, then it's not particularly meaningful (there's a note, but no lyrics to go with it, meaning there's not really any UI for even telling you when to do anything).

**Comment by jose1711** [comment]
Thank you for making it more forgiving to errors in UltraStar files, tested and works fine.
